# Generated by Django 4.2.11 on 2024-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(default=-1, help_text='in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.png', upload_to='recipes'),
        ),
    ]
